server:
  port: 8080

app:
  api-prefix: ${API_PREFIX:/api}
  api-prefix-v1: ${API_PREFIX_V1:/api/v1}
  api-prefix-v2: ${API_PREFIX_V2:/api/v2}
  api-insights: ${API_PREFIX_INSIGHTS:/api/insights}

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/api/v1/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:5173
              - https://localhost:3000
              - https://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
          '[/api/auth/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:5173
              - https://localhost:3000
              - https://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allowCredentials: true
          '[/api/insights/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:5173
              - https://localhost:3000
              - https://localhost:5173
            allowedMethods:
              - GET
              - POST
            allowed-headers: "*"
            allowCredentials: true
      routes:
        - id: ws_sock_info_route
          uri: lb://quizcards
          predicates:
            - Path=${app.api-prefix}/ws/info/**
          filters:
            - name: ReactiveAuthentication

        - id: ws_sock_route
          uri: lb://quizcards
          predicates:
            - Path=${app.api-prefix}/ws/**
          filters:
            - name: ReactiveAuthentication

        - id: notification_service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix-v1}/notification/**
          filters:
            - name: ReactiveAuthentication
            - name: StripPrefix
              args:
                parts: 2
            - name: PrefixPath
              args:
                prefix: /api/v1/ms

        - id: quizcards_auth
          uri: lb://quizcards
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - name: ReactiveAuthentication

        #        - id: quizcards_ws_auth
        #          uri: lb://quizcards
        #          predicates:
        #            - Path=${app.api-prefix}/ws/**, ${app.api-prefix}/auth/**
        #          filters:
        #            - name: ReactiveAuthentication

        - id: notification_testing_service
          uri: lb://notification-service-for-testing
          predicates:
            - Path=${app.api-prefix-v1}/notification-testing/**
          filters:
            - name: ReactiveAuthentication
            - name: StripPrefix
              args:
                parts: 2
            - name: PrefixPath
              args:
                prefix: /api/v1/ms

        - id: quizcards_general_service
          uri: lb://quizcards
          predicates:
            - Path=${app.api-prefix-v1}/**
          filters:
            - name: ReactiveAuthentication

        - id: block_security_internal
          uri: no://op          # dummy URI, sẽ không được gọi
          predicates:
            - Path=${app.api-insights}/security/internal/**
          filters:
            - name: SetStatus
              args:
                status: 403



eureka:
  instance:
    prefer-ip-address: true # Gửi IP thay vì hostname cho Eureka
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE_HTTP_METHOD:http}://${eureka.instance.hostname}:${EUREKA_SERVER_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true


services:
  security_service_url: "http://security-service/${app.api-insights}/security"

logging:
  level:
    org.springframework.web.cors: TRACE
    org.springframework.cloud.gateway.filter.cors: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway: TRACE