buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        // Cho Flyway plugin biết cách xử lý MySQL
        classpath "org.flywaydb:flyway-mysql:10.13.0"
        // JDBC driver MySQL
        classpath "com.mysql:mysql-connector-j:8.0.33"
    }
}


plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.flywaydb.flyway' version '10.13.0'
}

group = 'com.microservices'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url 'https://jitpack.io' }
    maven { url 'https://repo.spring.io/release' }
    maven { url 'https://repo.spring.io/milestone' }
}

ext {
    set('springCloudVersion', "2025.0.0-RC1")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'io.asyncer:r2dbc-mysql:1.4.1'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'com.github.lkienkle11:profile-filter-reactive:v0.1.4'
    implementation 'com.github.lkienkle11:shared-common-classes:v0.+'
    implementation 'com.github.lkienkle11:reactive-redis-utils:v0.1.6'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

flyway {
    // JDBC URL tới DB mà bạn muốn apply migrations
//	url      = project.findProperty('flyway.url')      ?: 'jdbc:mysql://localhost:3306/quizcards_demo_kien_1?createDatabaseIfNotExist=true'
//	user     = project.findProperty('flyway.user')     ?: 'root'
//	password = project.findProperty('flyway.password') ?: 'KiinGoldTRung0112'

    url      = project.findProperty('spring.flyway.url')      ?: ''
    user     = project.findProperty('spring.flyway.user')     ?: ''
    password = project.findProperty('spring.flyway.password') ?: ''

    // Nếu bạn đặt migrations trong thư mục khác, chỉ định lại
    locations = ['classpath:db/migration']
}

tasks.named('test') {
    useJUnitPlatform()
}