server:
  port: 8111

app:
  workflow_id_prefix: push_noti_

spring:
  application:
    name: streak-schedule-service
  config:
    import: optional:file:.env[.properties]
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
  r2dbc:
    url: ${R2DBC_URL}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  kafka:
    port: ${KAFKA_PORT:9092}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:${spring.kafka.port}}
    username: ${KAFKA_USERNAME:}
    password: ${KAFKA_PASSWORD:}
  temporal:
    namespace: ${TEMPORAL_NAMESPACE:default}

    connection:
      target: ${TEMPORAL_HOST:localhost}:${TEMPORAL_PORT:7233}

    workers:
      - task-queue: notification-schedule-queue
        capacity:
          max-concurrent-activity-executors: 5
          max-concurrent-workflow-task-executors: 3
      - rate-limits:
          max-worker-activities-per-second: 10
          max-task-queue-activities-per-second: 100

    workflow-cache:
      max-instances: 1
      max-threads: 2


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE_HTTP_METHOD:http}://${eureka.instance.hostname}:${EUREKA_SERVER_PORT}/eureka/
    #      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true # Gửi IP thay vì hostname cho Eureka
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

management:
  health:
    redis:
      enabled: true
    db:
      enabled: true