CREATE TABLE IF NOT EXISTS `set_progress_setting` (
                                        `sm_id` bigint NOT NULL AUTO_INCREMENT,
                                        `card_per_round` bigint NOT NULL,
                                        `consecutive_correct_bonus_factor` float NOT NULL,
                                        `consecutive_incorrect_penalty_factor_learning` float NOT NULL,
                                        `consecutive_incorrect_penalty_factor_relearning` float NOT NULL,
                                        `consecutive_incorrect_penalty_factor_review` float NOT NULL,
                                        `current_simple_mode_version` bigint NOT NULL,
                                        `current_srs_version` bigint NOT NULL,
                                        `custom_interval_again_seconds` bigint NOT NULL,
                                        `custom_interval_easy_seconds` bigint NOT NULL,
                                        `custom_interval_good_seconds` bigint NOT NULL,
                                        `custom_interval_hard_seconds` bigint NOT NULL,
                                        `interval_seconds_can_skip` int NOT NULL,
                                        `is_automatic_select_card` bit(1) NOT NULL,
    `lapse_new_interval_factor` float NOT NULL,
    `learning_steps` varchar(40) NOT NULL,
    `min_interval_gap` bigint NOT NULL,
    `new_cards_per_day` bigint NOT NULL,
    `ratio_mix` varchar(10) NOT NULL,
    `relearning_steps` varchar(40) NOT NULL,
    `sm2_hard_interval_factor` float NOT NULL,
    `sm2_interval_modifier` float NOT NULL,
    `user_id` bigint NOT NULL,
    `set_id` bigint NOT NULL,
    PRIMARY KEY (`sm_id`),
    KEY `idx_sps_user_id_set_id` (`user_id`,`set_id`),
    KEY `FKho8rq4na4qscsaemi8sdq4ndg_cascade` (`set_id`),
    CONSTRAINT `FKew4x4ael193e2kkuc0k0thfkt_cascade` FOREIGN KEY (`user_id`) REFERENCES `app_users` (`user_id`) ON DELETE CASCADE,
    CONSTRAINT `FKho8rq4na4qscsaemi8sdq4ndg_cascade` FOREIGN KEY (`set_id`) REFERENCES `set_flashcards` (`set_id`) ON DELETE CASCADE,
    CONSTRAINT `set_progress_setting_chk_1` CHECK (((`card_per_round` <= 256) and (`card_per_round` >= 1))),
    CONSTRAINT `set_progress_setting_chk_2` CHECK (((`interval_seconds_can_skip` >= 0) and (`interval_seconds_can_skip` <= 1200))),
    CONSTRAINT `set_progress_setting_chk_3` CHECK (((`new_cards_per_day` <= 256) and (`new_cards_per_day` >= 1)))
    ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;