spring.config.import=optional:file:.env[.properties]

app.context-path=${APP_CONTEXT_PATH:/api}

server.servlet.context-path=${app.context-path}

spring.application.name=${APP_NAME:quizcards}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DBMS_URL}
spring.datasource.username=${DBMS_USERNAME}
spring.datasource.password=${DBMS_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
server.port=${SERVER_PORT:8080}
spring.mvc.dispatch-options-request=true
jwt.secret=${SECRET_KEY}
jwt.jwtExpirationInSec=${AT_EXPIRED:7200}
jwt.refreshTokenExpirationInSec=${RF_EXPIRED:259200}

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Áp d?ng cho Java 21 và Spring Boot >= 3.2
spring.threads.virtual.enabled=true

spring.security.oauth2.client.registration.google.client-id=${OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH_URL_REDIRECT:{baseUrl}/login/oauth2/code/{registrationId}}
spring.security.oauth2.client.provider.google.authorization-uri=${OAUTH_AUTHOR_URI:https://accounts.google.com/o/oauth2/auth}
spring.security.oauth2.client.provider.google.token-uri=${OAUTH_TOKEN_URI:https://oauth2.googleapis.com/token}
spring.security.oauth2.client.provider.google.user-info-uri=${OAUTH_USERINFO_URI:https://www.googleapis.com/oauth2/v3/userinfo}
spring.security.oauth2.client.provider.google.user-name-attribute=sub

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yennhi0402dn@gmail.com
spring.mail.password=d s n j s w a s d k b e p p v t
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.smtp.auth=true
spring.mail.smtp.starttls.enable=true
spring.mail.debug=true

stripe.apiKey=${STRIPE_APIKEY_TEST}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DB}
spring.data.mongodb.auto-index-creation=true


file.storage.path=${STORAGE_PATH:D:/Downloads}

spring.jackson.serialization.indent-output=true

spring.cloud.compatibility-verifier.enabled=false

spring.notification.email.brevo-url=https://api.brevo.com
spring.notification.email.brevo-api-key=${BREVO_APIKEY}


spring.web-push-notifications.public-key=${WEB_PUSH_PUBLIC_KEY}
spring.web-push-notifications.private-key=${WEB_PUSH_PRIVATE_KEY}

#Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=${REDIS_CONNECT_TIMEOUT:60000}
spring.data.redis.lettuce.pool.max-active=${REDIS_POOL_MAX_ACTIVE:8}


app.brevo.template.id-otp=${BREVO_ID_OTP_TEMPLATE:1}
app.brevo.template.id-confirm-link=${BREVO_ID_CONFIRM_LINK:2}
app.email.default-system-email=${EMAIL_SYSTEM:mainfunction1234@gmail.com}
app.email.default-system-name=${NAME_SYSTEM:Quizcards System}

app.max-otp-attemp-mins=2

app.code-security-confirm=${CODE_SECURITY_CONFIRM}
app.link-frontend-client-confirm=${LINK_FRONTEND_CLIENT_CONFIRM}
app.code-expire-in-minutes=${CODE_EXPIRE_MINUTES:5}

app.critical-information.confirm-duration-hours=24
app.critical-information.changed-email-after-hours=24
app.critical-information.resend-email-after-secs=300

#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.consumer.group-id=my-group
#spring.kafka.consumer.properties.spring.json.trusted.packages=*

eureka.client.service-url.default-zone=${EUREKA_ZONE_HTTP_METHOD:http}://${eureka.instance.hostname}:${EUREKA_SERVER_PORT}/eureka/
#eureka.client.service-url.default-zone=http://localhost:8761/eureka/

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}

management.endpoints.web.exposure.include=health,info,mappings,secured-mappings,secured-mappings-search,secured-mappings-search-prefix

management.endpoint.mappings.enabled=true

management.endpoints.web.base-path=/actuator
management.endpoints.web.path-mapping.secured-mappings-search=secured-mappings/search
management.endpoints.web.path-mapping.secured-mappings-search-prefix=secured-mappings/search-prefix