spring:
  application:
    name: eureka-server
  config:
    import: optional:file:.env[.properties]

server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_ZONE_HTTP_METHOD:http}://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0